### ISSUE TITLE
DOCUMENTATATION CHECKLIST

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-template#31]
- [ ] remove all WIP / unfinished code from tests and everywhere else #32
- [ ] README is for the study
- [ ] move all engineering docs, to final unclear location
- [ ] engineering docs cover everything in https://github.com/mozilla/shield-studies-addon-utils/issues/93#issuecomment-341536970
